# Generated by Django 4.0.4 on 2022-05-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
